build-examples:
    cargo build --examples

apml-lex-all tree: build-examples
    QUIET=y find "{{tree}}" '(' -name 'spec' -or -name 'defines*' ')' \
        -print -exec ../target/debug/examples/apml-lex '{}' ';'

apml-emit-all tree: build-examples
    QUIET=y find "{{tree}}" '(' -name 'spec' -or -name 'defines*' ')' \
        -print -exec ../target/debug/examples/apml-emit '{}' ';'

apml-eval-all tree: build-examples
    QUIET=y find "{{tree}}" '(' -name 'spec' -or -name 'defines*' ')' \
        -print -exec ../target/debug/examples/apml-eval '{}' ';'
