build-examples:
    cargo build --examples

apml-lex-all-specs tree: build-examples
    #!/usr/bin/bash
    set -euo pipefail
    shopt -s globstar
    for file in "{{tree}}"/**/spec; do
        echo "$file"
        QUIET=y ../target/debug/examples/apml-lex "$file"
    done
